apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-docker-java
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/Believekhandal/docker-k8s.git'
    targetRevision: master
    path: dockerdemo/kubernetes-manifests
  project: default
  syncPolicy:
    automated: {}
