apiVersion: v1
kind: Service
metadata:
  name: k8s-docker-java
spec:
  type: NodePort
  selector:
    app: k8s-docker-java
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31136   # Kubernetes will expose this port
